### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by IvanDeLucasRog** [jamesrochabrun/SwiftOpenAI#11]
Please, can you provide an example on how to use the code interpreter assistant? In you demo project Im only able to configure it, but not to use it.

Thanks a lot

**Comment by gdeprodev** [comment]
Hello, when using the "listMessages" function of the Assistant (my Assistant uses the Retrieval tool), in case the response contains file citations, I receive an encoding error regarding the "type" key of "file_citation". How can I solve this? Thank you very much.

**Comment by jamesrochabrun** [comment]
Will take a look on that very soon.

**Comment by jamesrochabrun** [comment]
@IvanDeLucasRog I added a whole new demo on how to get use code interpreter using stream API check the Examples repo in the `AssistantThreadConfigurationProvider`

**Comment by jamesrochabrun** [comment]
@gdeprodev could you please share a JSON response? I will need that to verify if the decoding is correct, thanks!

**Comment by jamesrochabrun** [comment]
@gdeprodev I added an optimistic fix, let me know if that solves your issue https://github.com/jamesrochabrun/SwiftOpenAI/commit/293685e1d04d28214955bfe266067467e82ff4ac

**Comment by jamesrochabrun** [comment]
Closing this as:

1 - I added more examples for assistant and code retrieval
2- I added a fix for file citation decoding error.
