### ISSUE TITLE
api-key header instead of Authorization for Azure OpenAI

### ISSUE THREAD

**Issue by mfreiwald** [jamesrochabrun/SwiftOpenAI#12]
To use Azure OpenAI the requests needs to have an `api-key` header instead of `Authorization`

`api-key: YOUR_API_KEY`
instead of
`Authorization: Bearer YOUR_API_KEY` 

Edit:
I saw there are two ways to authenticate: api-key or Microsoft Entra ID 
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication

So maybe it would make sense to make this more clear in the implementation and possible to use both ways.

**Comment by jamesrochabrun** [comment]
Moving this conversation to https://github.com/jamesrochabrun/SwiftOpenAI/pull/13
