### ISSUE TITLE
Vapor Server side Swift + SwiftOpenAI + Fly.io: error: 'URLSessionConfiguration' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.

### ISSUE THREAD

**Issue by AlanDuong07** [jamesrochabrun/SwiftOpenAI#25]
Hi, I am building a backend API for my ios app using Vapor, a server side swift framework. I have successfully built the api and the SwiftOpenAI package was very useful. However, unfortunately when I tried to deploy the server to the world using Fly.io (which takes in a docker file and ships it to the world), I got a ton of errors regarding the import Foundation. 

Apparently, this is because Linux does not support URLSession. And apparently, I should avoid Foundation in general when it comes to server side swift.

Someone from the Vapor community told me I should be able to inject my own HTTP client. Is there any way to do this for this package?

And if not, I guess i'd have to fork this library and switch out the HTTP client for a different one? I don't know what to do here, could you possibly help?

Errors from Fly.io:
2.498 Building for production...
2.693 [0/881] Compiling a_utctm.c
2.707 [1/881] Compiling a_time.c
2.708 [2/881] Compiling _NumericsShims _NumericsShims.c
2.709 [3/881] Compiling a_type.c
3.456 [5/885] Compiling _NIOBase64 Base64.swift
4.280 [7/887] Compiling _NIODataStructures Heap.swift
4.363 [9/888] Compiling SwiftOpenAI AzureOpenAIAPI.swift
4.363 /build/.build/checkouts/SwiftOpenAI/Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift:14:32: error: 'URLSessionConfiguration' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
4.363       urlSessionConfiguration: URLSessionConfiguration = .default,
4.363                                ^~~~~~~~~~~~~~~~~~~~~~~
4.363 Foundation.URLSessionConfiguration:2:18: note: 'URLSessionConfiguration' has been explicitly marked unavailable here
4.363 public typealias URLSessionConfiguration = AnyObject
4.363                  ^
4.363 /build/.build/checkouts/SwiftOpenAI/Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift:14:59: error: type 'URLSessionConfiguration' (aka 'AnyObject') has no member 'default'
4.363       urlSessionConfiguration: URLSessionConfiguration = .default,
4.363                                                          ~^~~~~~~
4.363 /build/.build/checkouts/SwiftOpenAI/Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift:24:24: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
4.363    public let session: URLSession
4.363                        ^~~~~~~~~~
4.363 Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
4.363 public typealias URLSession = AnyObject

**Comment by AlanDuong07** [comment]
Edit: apparently Foundation is in fact supported on Linux. 

But yes, according to the error message it looks like we need to import FoundationNetworking as well.

Can i submit a PR that does: import FoundationNetworking under every import of "Foundation"?

**Comment by jamesrochabrun** [comment]
Hi! can you please be more specific:

> The problem I see though is that now, if anyone ever forgets to do this in a file (who maintains this package), it will crash again, for any people using SwiftOpenAI in a linux environment.

Does this mean if I add a new file where `Foundation` is needed it will cascade into a crash for any people using SwiftOpenAI in a Linux environment?

Is it correct to assume that with the current state of the package this is not usable on Linux correct?
If you propose to add :

```swift
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
```

in every file where 
```swift
import Foundation
```

I would need to review why is this needed, can you please share documentation and some repo where this is applied? I am not familiar with Vapor and I am not sure if that is the right approach. Thanks!
