### ISSUE TITLE
ToolChoice encoding for .function(type:name:) case

### ISSUE THREAD

**Issue by 54321rick** [jamesrochabrun/SwiftOpenAI#26]
It seems that ChatCompletionParameters.ToolChoice.function(type:name:) may not be being encoded to match what API is expecting. 

If I do this in Chat completion parameters:

toolChoice: ChatCompletionParameters.ToolChoice.function(type: "function", name: "eight_ball_responder")

It looks like the JSON sent to the API is:
{
  "name": "eight_ball_responder",
  "type": "function"
}

But the API wants:
{
  "type": "function",
  "function": {"name": "my_function"}
}

The API responds, "400 'tool_choice' is invalid"

The tool definition itself compiles and is used by OpenAI with expected results if I leave tool_choice at "auto," so I don't think it's a problem with the tool itself. The issue appears to be specifically with the .function(type:name:) instruction.

Apologies in advance if I am mistaken here!

**Comment by jamesrochabrun** [comment]
Thanks for letting me know, added a fix here https://github.com/jamesrochabrun/SwiftOpenAI/pull/27
Let me know how it goes!

**Comment by 54321rick** [comment]
Thanks James!

**Comment by 54321rick** [comment]
Your content and this package are very helpful. Your contribution to
advancing all of us is APPRECIATED!
Best,
Rick
