### ISSUE TITLE
Speed 

### ISSUE THREAD

**Issue by cdahllof** [jamesrochabrun/SwiftOpenAI#38]
Hi James,

Thanks for creating an repo that is up to date with OpenAI API. It made it easy  to create a voice assistant.

I am working on speeding up the app and wondering if you have any suggestions. 

Thanks!

caro

**Comment by jamesrochabrun** [comment]
What do you mean exaclty? is a personal app? What do you want to optimize?

**Comment by cdahllof** [comment]
I have created a personal app. It is very simple, I have an AI assistant that you can speak to and it replies. It takes many seconds to get a response. What is a normal response time?

**Comment by jamesrochabrun** [comment]
The delay is understandable as you may be using speech to text first, then making a request to completion API, wait for the response and then making a new request to text to speech. 
There is no much you can do now, but good news are that soon you will be able to do all using gtp 4 O model which it will make this process faster. Good luck!

**Comment by cdahllof** [comment]
Thanks James.
