### ISSUE TITLE
I keep getting an error when i am using gpt4o

### ISSUE THREAD

**Issue by Abdulganiylawal** [jamesrochabrun/SwiftOpenAI#39]
This is the code that converts an image to base 64
`    private func handleFileImport(result: Result<URL, Error>) {
        DispatchQueue.global(qos: .userInitiated).async {
            do {
                let fileUrl = try result.get()
                guard fileUrl.startAccessingSecurityScopedResource() else { return }

                defer { fileUrl.stopAccessingSecurityScopedResource() }

                let imageData = try Data(contentsOf: fileUrl)
                guard let image = UIImage(data: imageData) else { return }
                
                let base64String = imageData.base64EncodedString()
                let dataUrlString = "data:image/jpeg;base64,\(base64String)"
                DispatchQueue.main.async {
                    self.selectedImageURLS.append(dataUrlString)
                    self.selectedImages.append(Image(uiImage: image))
                    self.showOthers = false
                    print("Selected Image URLs: \(self.selectedImageURLS)")
                }
            } catch {
                DispatchQueue.main.async {
                    print("Error reading")
                    print(error.localizedDescription)
                }
            }
        }
    }`

This is the vision API code 
   let content: [ChatCompletionParameters.Message.ContentType.MessageContent] = [.text(message)] + selectedImageURLS.map { .imageUrl(URL(string: $0 )!)}

This is the error I keep receiving 

responseUnsuccessful(description: "status code 400 Invalid type for \'messages[0].content[1].image_url\': expected an object, but got a string instead.")

**Comment by jamesrochabrun** [comment]
What happens if you change the model to "gpt-4-vision-preview" ?

Can you show your request?

**Comment by Abdulganiylawal** [comment]
It works for gpt4 vision preview

**Comment by jamesrochabrun** [comment]
fixed https://github.com/jamesrochabrun/SwiftOpenAI/releases/tag/v2.9
