### ISSUE TITLE
Looking for advice using Assistant API / Tool/ Run - waiting for 'required action' state

### ISSUE THREAD

**Issue by vade** [jamesrochabrun/SwiftOpenAI#45]
Hi

Firstly, this library is really great. Thank you! 

Im successfully able to set up an assistant, assign it tools, and have my assistant make tool choices based off of the provided tools in JSON format reliably. 

Some code:

```
         let threadParam = CreateThreadParameters()
        let thread = try await self.service.createThread(parameters: threadParam)
        
        let messageParameters = MessageParameter(role: .user, content: "some user prompt)
        let message = try await self.service.createMessage(threadID: thread.id, parameters: messageParameters)

        let runParameters = RunParameter(assistantID: assistant.id)
        var run = try await self.service.createRun(threadID: thread.id, parameters: runParameters)
        
        while run.status != "requires_action"
        {
            run = try await self.service.retrieveRun(threadID: thread.id, runID: run.id)
            print("waiting for completion")
            sleep(1)
        }

        print("got completion")

```

What im curious about is how to effectively understand when a run's status has changed without a polling like model? Is there any method of a callback or some request parameter to stall a response until the response is anything other than in progress? I don't quite like the idea of sleeps or polling in my async code for whatever reason. 

Im trying to wrap my head around a nice abstraction to create a thread and provide tool responses in a loop for something akin to a  Chain Of Chain of thought  / Re-Act style approach.

Thank you!

**Comment by jamesrochabrun** [comment]
I recommend using stream instead, you can rely on the stream events to know the state of a run.
I added support for that here https://github.com/jamesrochabrun/SwiftOpenAI/commit/cca9a9e82d925009c8460e3faf8413d1e8cd677f
You can check the demo as well. https://github.com/jamesrochabrun/SwiftOpenAI/blob/main/Examples/SwiftOpenAIExample/SwiftOpenAIExample/Assistants/AssistantThreadConfigurationProvider.swift#L82

**Comment by vade** [comment]
Thanks @jamesrochabrun - I'll look into implementing Stream. Much obliged!
