### ISSUE TITLE
Make it possible to pass in custom API host

### ISSUE THREAD

**Issue by sindresorhus** [jamesrochabrun/SwiftOpenAI#51]
There are some services that are API compatible with OpenAI. For example, [Ollama](https://ollama.com/blog/openai-compatibility).

I would add an optional `apiHost` parameter:

```swift
OpenAIServiceFactory.service(apiKey: apiKey, organizationID: oganizationID, apiHost: URL(string: "http://localhost:11434")!)
```

**Comment by jamesrochabrun** [comment]
That is an interesting idea, I had not played with local models yet.
I can extend this, can you please educate me how does local models are used?
I understand that users can download the model to run them locally but can they also be added i to the bundle of an ios mac app?  
Thanks!

**Comment by jamesrochabrun** [comment]
Done! https://github.com/jamesrochabrun/SwiftOpenAI/releases/tag/v3.3

Thanks for the idea @sindresorhus !

**Comment by benadamdev** [comment]
Wow, that was a fast implementation @jamesrochabrun. Thank you. Any thoughts on https://github.com/PreternaturalAI

**Comment by sindresorhus** [comment]
@jamesrochabrun Thanks for the quick implementation. Unfortunately, this does not fully solve my need. In my app, I allow users to specify their own "base URL". Ollama was just an example. There could be other services that are API-compatible with OpenAI, and that may require an API key. So it would be great if either `.service()` could also receive a `baseURL` parameter or publicly expose `DefaultOpenAIService`.

**Comment by jamesrochabrun** [comment]
@sindresorhus Can you please try to test your use case using this constructor?

```swift
let service = OpenAIServiceFactory.ollama(baseURL: "your_local_host_url")
```

I think that the `ollama` name may be confusing here but you can use any URL. Give it a try and I can probably make this constructor to be ...

```swift
let service = OpenAIServiceFactory.service(baseURL: "your_local_host_url")
```

Also if you can share more details about your use case, I am happy to support you.

**Comment by sindresorhus** [comment]
I need to be able to pass in an API key too, even when using a custom `baseURL`.

So:

```swift
OpenAIServiceFactory.service(apiKey: apiKey, baseURL: URL(string: "http://localhost:11434")!)
```

would be the best.
