### ISSUE TITLE
Please add model support for gpt-4o-mini

### ISSUE THREAD

**Issue by codehearted** [jamesrochabrun/SwiftOpenAI#61]
GPT-4o-mini is now available via API and is by far the most cost-efficient model. All that's needed is to add a new enum key linked to the string "gpt-4o-mini" for the dynamically retargeting model, and another for "gpt-4o-mini-2024-07-18" for the version that will not dynamically update as new models are released.

For App authors, this model is extremely desirable to start working with ASAP.

Here's a link to the OpenAI reference document section: 
https://platform.openai.com/docs/models/gpt-4o-mini

And the relevant announcement:
https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/

Thanks in advance.

**Comment by jamesrochabrun** [comment]
https://github.com/jamesrochabrun/SwiftOpenAI/releases/tag/v3.5

Done!

**Comment by codehearted** [comment]
Thank you! I was going to submit a PR but you beat me to it!
