### ISSUE TITLE
Not working createThreadAndRun / createThreadAndRunStream

### ISSUE THREAD

**Issue by crash481** [jamesrochabrun/SwiftOpenAI#66]
Tried to run Assistants api method that created thread and run in same function, but gets error 
`THREAD ERROR: responseUnsuccessful(description: "status code 400 You must provide the \'OpenAI-Beta\' header to access the Assistants API. Please try again by setting the header \'OpenAI-Beta: assistants=v2\'.", statusCode: 400)`

The problem that in method `service.createRunStream and service.createRun` you add `betaHeaderField: Self.assistantsBetaV2`
But in method `service.createThreadAndRun and service.createThreadAndRunStream` not

But this methods is very convenience. It is good to have option to start new thread with start user message and run it oneline

**Comment by jamesrochabrun** [comment]
Thanks for your report, fixed here https://github.com/jamesrochabrun/SwiftOpenAI/pull/69
