### ISSUE TITLE
The Azure OpenAI API does not support stream_options.

### ISSUE THREAD

**Issue by ipevo-Kevin** [jamesrochabrun/SwiftOpenAI#67]
SwiftOpenAI works fine in version 3.0. However, starting with version 3.1, startStreamedChat returns the following error: Error: responseUnsuccessful(description: "status code 400 Unknown parameter: 'stream_options'.").

The data returned from the Azure OpenAI Server is as follows:
{
  "error": {
    "message": "Unknown parameter: 'stream_options'.",
    "type": "invalid_request_error",
    "param": "stream_options",
    "code": "unknown_parameter"
  }
}

**Comment by jamesrochabrun** [comment]
Thanks so much for the detail info
Fixed here https://github.com/jamesrochabrun/SwiftOpenAI/pull/68
