### ISSUE TITLE
RunToolsOutputParameter.ToolOutput' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by AlanDuong07** [jamesrochabrun/SwiftOpenAI#7]
Hello, when I try to Submit Tool Outputs to Run, it gives me this error:
RunToolsOutputParameter.ToolOutput' initializer is inaccessible due to 'internal' protection level
'RunToolsOutputParameter' initializer is inaccessible due to 'internal' protection level

Code:

let output = "PLACEHOLDER: Success"
let parameters = RunToolsOutputParameter(toolOutputs: [.init(toolCallId: toolCall.id, output: output)])
let run = try await service.submitToolOutputsToRun(threadID: threadId, runID: run.id, parameters: parameters)

**Comment by jamesrochabrun** [comment]
Thanks for flagging, this should fix the issue https://github.com/jamesrochabrun/SwiftOpenAI/pull/8
