### ISSUE TITLE
aiproxyServiceURL is not registering 

### ISSUE THREAD

**Issue by tc-cole** [jamesrochabrun/SwiftOpenAI#71]
let service = OpenAIServiceFactory.service(
        aiproxyPartialKey: "your_partial_key_goes_here",
        aiproxyServiceURL: "your_service_url_goes_here"
    )

**Comment by lzell** [comment]
Hi @tc-cole , can you explain what you mean by 'not registering'?

**Comment by tc-cole** [comment]
in XCode, the aiproxyServiceUrl has errors in it.

**Comment by lzell** [comment]
I have a suspicion you are hitting the same problem as another poster, where your SwiftOpenAI package is out of date. Can you take a look at this comment and see if it helps you: 
https://github.com/jamesrochabrun/SwiftOpenAI/issues/60#issuecomment-2240810292

The latest version of SwiftOpenAI is 3.6.2. If you look in your project tree (View > Navigators > Project) and look at the SwiftOpenAI dependency, which version do you see there?

**Comment by tc-cole** [comment]
Yeah that is the problem

**Comment by tc-cole** [comment]
Just updated the package, and I am sitll getting the same error

Extra argument 'aiproxyServiceURL' in call

**Comment by lzell** [comment]
In your project navigator, does the SwiftOpenAI package say either `3.6.2` or `e4b6405` (which is the latest commit on `main`): 
![Screenshot 2024-08-06 at 16 27 37](https://github.com/user-attachments/assets/50f87d87-af23-40a1-b8fc-72a08665982a)

Or

![Screenshot 2024-08-06 at 16 27 59](https://github.com/user-attachments/assets/a26ac7b0-3099-4982-92b7-1803244ae5e8)

If so, please go to `File > Packages > Reset Package Caches` and build again.

If your package does not match one of those screenshots
![Screenshot 2024-08-06 at 16 31 07](https://github.com/user-attachments/assets/884421f4-6789-43b2-8b32-784dfff18ac3)
, then you can adjust the rule at:

**Comment by tc-cole** [comment]
I am still getting the same error.
<img width="1707" alt="Screenshot 2024-08-07 at 4 16 25 PM" src="https://github.com/user-attachments/assets/9bcf3ae2-86de-401e-be75-95f12d55872c">

(please note this is noy my actual apikeys)

**Comment by lzell** [comment]
That's really confusing, because the parameter is certainly there: https://github.com/jamesrochabrun/SwiftOpenAI/blob/main/Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift#L87

🤔 

Can you try doing this:
`let service: OpenAIService = OpenAIServiceFactory.service(aiproxyPartialKey: "", aiproxyServiceURL: "")` and see if that compiles?

**Comment by tc-cole** [comment]
I tried doing that as well, to no avail.

**Comment by lzell** [comment]
So weird! If you use cmd-shift-o and type in OpenAIServiceFactory. Then scroll to the aiproxy factory method and take a screenshot to share here?

**Comment by tc-cole** [comment]
I’m out right now, do you have a business email so we can set up a call?

**Comment by lzell** [comment]
Yup, I emailed you an hour or so ago. Look for lou[at]aiproxy

**Comment by lzell** [comment]
@tc-cole nice chatting with you today! Sorry you were seeing such confusing error messages

@jamesrochabrun we can close this ticket, as it's been resolved by https://github.com/jamesrochabrun/SwiftOpenAI/pull/73

**Comment by tc-cole** [comment]
Thank you so much! If you ever need a testimonial please find me!

**Comment by lzell** [comment]
@tc-cole  🤝
