### ISSUE TITLE
Getting `usage` for streamed responses

### ISSUE THREAD

**Issue by gdbing** [jamesrochabrun/SwiftOpenAI#82]
> You can get token usage statistics for your streamed response by setting stream_options={"include_usage": True}. When you do so, an extra chunk will be streamed as the final chunk. You can access the usage data for the entire request via the usage field on this chunk.

https://cookbook.openai.com/examples/how_to_stream_completions#4-how-to-get-token-usage-data-for-streamed-chat-completion-response

**Comment by jamesrochabrun** [comment]
This is available in latest release v3.7.0 can you see if it is what you need please?
