### ISSUE TITLE
release version v3.4.0 less than v3.6.2

### ISSUE THREAD

**Issue by JadenGeller** [jamesrochabrun/SwiftOpenAI#83]
I think this was a mistake, but I might be missing something. The latest release was version v3.4.0, but a previous release was v3.6.2.

I noticed this because I couldn't understand why `ResponseFormat.jsonSchema` was missing from the version Xcode fetched after updating to the latest version.

I can just depend on v3.4.0 directly, but I suspect this was a mistake, so I wanted to flag. Thank you!

**Comment by jamesrochabrun** [comment]
latest is v3.4.0 , thanks for flagging.

**Comment by lzell** [comment]
Hey @jamesrochabrun you may want to bump a version to 3.6.3 or 3.7.0, even if it's an empty release. Otherwise folks adding the package are going to get version 3.6.2 which does not have your latest release (3.4.0). E.g. the Xcode semver check is going to place 3.6.2 above 3.4.0 (latest)

**Comment by jamesrochabrun** [comment]
@lzell thanks for catching! 😱

**Comment by lzell** [comment]
All credit goes to @JadenGeller . I noticed some package resolution errors in Xcode as well. Happy to see you took out 3.7.0

**Comment by jamesrochabrun** [comment]
thanks @JadenGeller for flagging!! really appreciate the collaboration
