### ISSUE TITLE
MessageParameter content is always a String

### ISSUE THREAD

**Issue by ADiamondDeveloper** [jamesrochabrun/SwiftOpenAI#88]
Currently, MessageParameter `content` is always a string. Could you update it to allow more flexibility, similar to the `content` in [createMessage](https://platform.openai.com/docs/api-reference/messages/createMessage), since messages might need to handle different types of content?

From:` let content: String`

To: `let content: [ContentPart]`, allowing for `text`, `image_file`, and `image_url` objects."

**Comment by jamesrochabrun** [comment]
Fixed https://github.com/jamesrochabrun/SwiftOpenAI/pull/92
