### ISSUE TITLE
Multi-turn conversations for Audio generation with generated ID 

### ISSUE THREAD

**Issue by cdahllof** [jamesrochabrun/SwiftOpenAI#96]
I am wondering if I can pass the generated ID for multi-turn conversation: Let me know. 

https://platform.openai.com/docs/guides/audio/multi-turn-conversations?audio-generation-quickstart-example=audio-in
curl "https://api.openai.com/v1/chat/completions" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d '{
        "model": "gpt-4o-audio-preview",
        "modalities": ["text", "audio"],
        "audio": { "voice": "alloy", "format": "wav" },
        "messages": [
            {
                "role": "user",
                "content": "Is a golden retriever a good family dog?"
            },
            {
                "role": "assistant",
                **"audio": {
                    "id": "audio_abc123"
                }**
            },
            {
                "role": "user",
                "content": "Why do you say they are loyal?"
            }
        ]
    }'

**Comment by jamesrochabrun** [comment]
available now https://github.com/jamesrochabrun/SwiftOpenAI/releases/tag/v3.9.1

**Comment by cdahllof** [comment]
Thank you James!
